# Generated by Django 2.2.6 on 2019-11-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
