# Generated by Django 2.2.6 on 2019-11-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliver',
            name='order',
        ),
        migrations.AddField(
            model_name='deliver',
            name='reciverName',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
