# Generated by Django 2.2.6 on 2019-11-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_deliver_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliver',
        ),
    ]
