# Generated by Django 2.2.6 on 2019-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
