# Generated by Django 2.2.6 on 2019-11-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
    ]
